#!/bin/bash
set -e

source "$(dirname "$0")"/version
cd "$(dirname "$0")"/..

KERNEL_DIR=build/kernel

set -x

# kernel
rsync -aP "${DOWNLOADS}/kernel/" "${KERNEL_DIR}/"

# patches
if [ -n "${NOPATCHES}" ]; then
    exit 0
fi
PATCHES_DIR=$(pwd)/patches
pushd ${KERNEL_DIR}

for p in "${PATCHES_DIR}"/*.patch; do
    echo "applying $p"
    patch -p1 -i "$p"
done
popd
